[tool.poetry]
name = "fast-test-database"
version = "0.0.0"
description = "Configure an in-memory database for running Django tests"
authors = ["Alexey Kotlyarov <a@koterpillar.com>"]
license = "GPL-3.0-or-later"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.0"

[tool.poetry.dev-dependencies]
mysqlclient = "^2.0.3"
psycopg2 = "^2.9.1"
pycodestyle = "^2.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
